[package]
name = "imagebox"
description = "command line image utility"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/amitmaish/imagebox.git"

[dependencies]
image = "0.25.5"
rand = "0.8.5"

